development:
  adapter: postgresql
  encoding: utf8
  database: ecv_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: ecv_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ecv_production
  pool: 5
  username: 
  password:
